### PR TITLE
Update uuid to 0.6

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Hey

Updating this crate to 0.6 since the new release is out. There are no further changes required.

### CODE REVIEW

**Comment by awestlake87** [comment]
Hey, I'm sorry for the late response, I've been busy with 0.4 changes and migrating the project source to GitLab. I'll update the Cargo.toml and try and get a 0.3.3 release with it published to crates.

**Comment by awestlake87** [comment]
Also, 0.4.0-alpha is in the works and will no longer depend on organelle or uuid, so that's also an option. It will require a lot of changes to go from 0.3 to 0.4, but in the long run, I think 0.4 is a much better setup.

**Comment by Dylan-DPC-zz** [comment]
Sounds good :+1:

**Comment by awestlake87** [comment]
0.3.3 is up on crates.io with uuid 0.6.

**Comment by awestlake87** [comment]
And 0.4.0-alpha.1 is up on crates.io with no uuid or organelle dependencies now. I'm gonna close this issue now, but let me know if you have any issues with it. Thanks for your patience, I'll try to respond quicker next time.

**Pull request closed without merging**
